let data = [
    {id: 0,
        name: "Moose",
        description: "This is Moose. He’s wondering where Santa’s reindeer tryouts are. Knows he has what it takes. 12/10 please point him in the right direction",
        src: "https://pbs.twimg.com/media/FGINqdpUcAItVF-?format=jpg&name=medium",
        clicked: false,
        class: "moose-image",
        rating: "12/10"
    }, 
    {id: 1,
        name: "Libby",
        description: "This is Libby. She had a scab on her nose and when it healed, it left a perfect pink heart. A target for your smooches, if you will. 14/10 ",
        src: "https://pbs.twimg.com/media/FGBl8EnVIAQapt0?format=jpg&name=900x900 ",
        clicked: false,
        class: "moose-image",
        rating: "14/10"
    }, 
    {id: 2,
        name: "Howdy",
        description: "This is Howdy. He’s the new sheriff. I know he’s not like super intimidating but please respect his authority. He gets grumpy if you don’t. 12/10 ",
        src: "https://pbs.twimg.com/media/FF94UlwVQAUpkTW?format=jpg&name=small",
        clicked: false,
        class: "moose-image",
        rating: "12/10"
    },
    {id: 3,
        name: "Teddy",
        description: "This is Teddy. He’s found several clues that indicate there’s a good boy around here somewhere. Maybe you’ve seen him. 14/10",
        src: "https://pbs.twimg.com/media/FFihj9DVEAA59tv?format=jpg&name=medium",
        clicked: false,
        class: "moose-image",
        rating: "14/10"
    },   
    {id: 4,
        name: "Roxie",
        description: "I accidentally kicked the back of this guy’s seat and now he won’t stop making faces at me. Idk what he wants. 14/10 ",
        src: "https://pbs.twimg.com/media/FE-ixZyUcAQpORn?format=jpg&name=small",
        clicked: false,
        class: "moose-image",
        rating: "14/10"
    },   
    {id: 5,
        name: "Baxter",
        description: "This is Baxter. He’s going to need a lot of attention today. He can just tell. 14/10 ",
        src: "https://pbs.twimg.com/media/FE5W6_GVEAIDEbu?format=jpg&name=medium",
        clicked: false,
        class: "moose-image",
        rating: "14/10"
    }, 
    {id: 6,
        name: "Chevy",
        description: "This is Chevy. He doesn’t mind the colder weather because he gets to wear his hoodie. It’s very cozy. 13/10",
        src: "https://pbs.twimg.com/media/FEQmvf7UUAAoNLj?format=jpg&name=medium",
        clicked: false,
        class: "moose-image",
        rating: "13/10"
    },
    {id: 7,
        name: "Titus and Roo",
        description: "This is Titus and Roo. Titus doesn’t stop drooling so Roo got a raincoat for when they hang out. It seems dramatic but it’s not. 13/10 for both ",
        src: "https://pbs.twimg.com/media/FD8-BDWVkAst1pN?format=jpg&name=small ",
        clicked: false,
        class: "moose-image",
        rating: "13/10"
    },   
    {id: 8,
        name: "Dino",
        description: "Seriously? We only rate dogs. This is a velociraptor. She won’t hurt you she is just startled. Please send dogs only. Thank you… 13/10 ",
        src: "https://pbs.twimg.com/media/FD7c-_3VUAI8UQk?format=jpg&name=medium ",
        clicked: false,
        class: "moose-image",
        rating: "13/10"
    },  
    {id: 9,
        name: "Louie",
        description: "This is Louie. He’s been catching flights while you’ve been catching feelings. 12/10 embarrassing for you",
        src: "https://pbs.twimg.com/media/FD21u10UUAIMTxs?format=jpg&name=small",
        clicked: false,
        class: "moose-image",
        rating: "12/10"
    }, 
    {id: 10,
        name: "Nova",
        description: "This is Nova. She’s an amateur bandana model trying to break into the professional scene. 14/10 we believe in you sweetie",
        src: "https://pbs.twimg.com/media/FDxU0gZX0AgL6Yv?format=jpg&name=large ",
        clicked: false,
        class: "moose-image",
        rating: "12/10"
    },
    {id: 11,
        name: "Kabosu",
        description: "This is Kabosu. She just turned 16 years old. She’s a rescue Shiba Inu who changed the world with an impromptu photoshoot back in 2010. Her slightly raised eyebrows and crossed paws remain one the greatest reaction images of all time. 15/10 such legend much wow",
        src: "https://pbs.twimg.com/media/FDOdLmKVQAIStvp?format=jpg&name=small ",
        clicked: false,
        class: "moose-image",
        rating: "15/10"
    } 
]

export default data 
